/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1;

public class Library {
	
	public static void main(String[] args) {
		Library lib = new Library();
		if (lib.someLibraryMethod()) {
			System.out.println("hello world");
		}
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
